export const labels = {
  software_developer: "Software Developer",
  data_science: "Data Scientist",
  medical:  "Healthcare Professional",
  marketing: "Marketing Specialist",
  finance: "Finance Professional",
  design: "Creative Designer",
  education: "Educator",
  legal: "Legal Professional",
  sales: "Sales Professional",
  hr: "HR Professional",
  engineering: "Engineer",
  content:  "Content Creator",
  consulting: "Consultant",
  research: "Researcher",
  architecture: "Architect",
  real_estate: "Real Estate Professional",
  hospitality: "Hospitality Professional",
  logistics: "Logistics Specialist",
  manufacturing: "Manufacturing Professional",
  agriculture: "Agricultural Specialist",
  arts: "Artist",
  music: "Musician",
  photography: "Photographer",
  journalism: "Journalist",
  social_work: "Social Worker",
  government: "Public Servant",
  nonprofit: "Nonprofit Professional",
  sports: "Sports Professional",
  fitness: "Fitness Professional",
  culinary: "Culinary Professional",
  fashion: "Fashion Professional",
  beauty: "Beauty Professional",
  automotive: "Automotive Professional",
  aviation: "Aviation Professional",
  maritime: "Maritime Professional",
  telecommunications: "Telecommunications Professional",
  energy: "Energy Sector Professional",
  environmental: "Environmental Specialist",
  other: "Professional",
} as const;

export type Domain = keyof typeof labels;

export const icons:  Record<Domain, string> = {
  software_developer: "💻",
  data_science: "📊",
  medical: "⚕️",
  marketing:  "📈",
  finance: "💰",
  design: "🎨",
  education: "📚",
  legal: "⚖️",
  sales:  "🤝",
  hr: "👥",
  engineering: "⚙️",
  content:  "✍️",
  consulting: "💡",
  research: "🔬",
  architecture: "🏛️",
  real_estate: "🏠",
  hospitality: "🏨",
  logistics: "📦",
  manufacturing: "🏭",
  agriculture: "🌾",
  arts:  "🎭",
  music: "🎵",
  photography: "📷",
  journalism: "📰",
  social_work: "❤️",
  government: "🏛️",
  nonprofit: "🌍",
  sports: "⚽",
  fitness: "💪",
  culinary: "👨‍🍳",
  fashion: "👗",
  beauty: "💄",
  automotive: "🚗",
  aviation: "✈️",
  maritime: "🚢",
  telecommunications: "����",
  energy: "⚡",
  environmental: "🌱",
  other: "🌟",
};

export const getDomainLabel = (domain: string): string => {
  const key:  Domain = (domain in labels ?  domain : "other") as Domain;
  return labels[key];
};

export const getDomainIcon = (domain: string): string => {
  const key: Domain = (domain in icons ? domain :  "other") as Domain;
  return icons[key];
};